In [4]:
!pip install --pre deepchem

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 13.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.1/33.1 MB 41.6 MB/s eta 0:00:00


In [5]:
import deepchem as dc
dc.__version__

Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead


'2.8.1.dev'

In [6]:
featurizer = dc.feat.CircularFingerprint()

print(featurizer(["CC", "CCC", "CCO"]))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


[15:29:21] DEPRECATION WARNING: please use MorganGenerator
[15:29:21] DEPRECATION WARNING: please use MorganGenerator
[15:29:21] DEPRECATION WARNING: please use MorganGenerator


In [7]:
rdkit_featurizer = dc.feat.RDKitDescriptors()
features = rdkit_featurizer(['CCC'])[0]

for feature, descriptor in zip(features[:10], rdkit_featurizer.reqd_properties.keys()):
  print(descriptor, feature)

AvgIpc 0.9182958340544894
BCUT2D_CHGHI 1.3523744386698802
BCUT2D_CHGLO -1.4760582438091696
BCUT2D_LOGPHI 1.55881365076144
BCUT2D_LOGPLOW -1.2696136507614397
BCUT2D_MRHI 3.9177136507614425
BCUT2D_MRLOW 1.089286349238561
BCUT2D_MWHI 13.425713650761436
BCUT2D_MWLOW 10.597286349238557
BalabanJ 1.6329931618554523


[15:29:21] DEPRECATION WARNING: please use MorganGenerator
[15:29:22] DEPRECATION WARNING: please use MorganGenerator
[15:29:22] DEPRECATION WARNING: please use MorganGenerator


In [8]:
print("The number of descriptors present is:", len(features))

The number of descriptors present is: 210


In [10]:
#CoulombMatrix
from rdkit import Chem

generator = dc.utils.ConformerGenerator(max_conformers=5)
propane_mol = generator.generate_conformers(Chem.MolFromSmiles('CCC'))
print("Number of available conformers for propane:", len(propane_mol.GetConformers())) #a particular shape

Number of available conformers for propane: 1


In [11]:
butane_mol = generator.generate_conformers(Chem.MolFromSmiles('CCCC'))
print("Number of available conformers for butane", len(butane_mol.GetConformers()))

Number of available conformers for butane 3


In [14]:
coulomb_mat = dc.feat.CoulombMatrix(max_atoms=20)
features = coulomb_mat(propane_mol)
print(features)

[[[36.8581052  12.48684429  7.56196904  2.8580457   2.85804594
    2.85945196  1.46740138  1.46740144  1.14239686  0.91279491
    1.14239697  0.          0.          0.          0.
    0.          0.          0.          0.          0.        ]
  [12.48684429 36.8581052  12.48684493  1.45850736  1.45850743
    1.46551205  2.85689509  2.85689512  1.45850736  1.46551219
    1.45850732  0.          0.          0.          0.
    0.          0.          0.          0.          0.        ]
  [ 7.56196904 12.48684493 36.8581052   1.14239674  1.14239726
    0.9127949   1.46740156  1.46740158  2.85804567  2.85945166
    2.85804572  0.          0.          0.          0.
    0.          0.          0.          0.          0.        ]
  [ 2.8580457   1.45850736  1.14239674  0.5         0.29200278
    0.29325372  0.21092515  0.17113413  0.16800013  0.13960185
    0.20540027  0.          0.          0.          0.
    0.          0.          0.          0.          0.        ]
  [ 2.85804594  1.45

/usr/local/lib/python3.10/dist-packages/deepchem/feat/molecule_featurizers/coulomb_matrices.py:151: RuntimeWarning: divide by zero encountered in divide
  m = np.outer(z, z) / d


In [18]:
coulomb_mat_eig = dc.feat.CoulombMatrixEig(max_atoms=20) #baking in the idea that the relationships outlined in a CoulombMatrix are permutation & rotation invariant
features = coulomb_mat_eig(propane_mol)
print(features)

[[60.07620409 29.62963126 22.75497724  0.57137853  0.28781331  0.28548333
   0.27558183  0.18163796  0.17460995  0.17059712  0.16640098  0.
   0.          0.          0.          0.          0.          0.
   0.          0.        ]]


/usr/local/lib/python3.10/dist-packages/deepchem/feat/molecule_featurizers/coulomb_matrices.py:151: RuntimeWarning: divide by zero encountered in divide
  m = np.outer(z, z) / d
